workspace:
  base: /go
  path: spiderGo

pipeline:
  build:
    image: golang:latest
    commands:
      # 解决依赖
    - go env -w GOPROXY="https://goproxy.cn"
    - go mod init spidergo
    - echo module github.com/x/y >> go.mod
    - echo go 1.14 >> go.mod
    - echo require ( >> go.mod
    - echo     github.com/gocolly/colly/v2 latest >> go.mod
    - echo )  >> go.mod
    # - go mod tidy
    
      #编译并执行
    - go run maotai.go