workspace:
  base: /go
  path: spriderGo/test

pipeline:
  build:
    image: golang:latest
    commands:
      - go env -w GOPROXY=https://goproxy.cn
      - go mod init spriderGo/test
      - go build rate_limit.go
      