workspace:
  base: /go
  path: spriderGo

pipeline:
  build:
    image: golang:1.4
    commands:
    - go env -w GOPROXY="https://goproxy.cn"
    # - go env -w GO111MODULE="auto"
    - go mod tidy
    - go run rate_limit.go