workspace:
  base: /go
  path: spriderGo

pipeline:
  build:
    image: golang:latest
    commands:
      - go env -w GOPROXY=https://goproxy.cn
      - go mod init spriderGp
      - go build rate_limit.go
      