workspace:
  base: /go
  path: spriderGo

pipeline:
  build:
    image: golang:latest
    commands:
      - go env -w GOPROXY=https://goproxy.cn
      - mkdir mod
      - go mod init spriderGp/mod
      - go run rate_limit.go
      