workspace:
  base: /go
  path: spiderGo

pipeline:
  build:
    image: golang:latest
    commands:
      # 解决依赖
    - go env -w GOPROXY="https://goproxy.cn"
    - go mod tidy
    
    #编译并执行
    # - go run request_context.go
    - go run maotai_test.go