workspace:
  base: /go
  path: spriderGo

pipeline:
  build:
    image: golang:latest
    commands:
    - echo test
    # - go env -w GOPROXY=GOPROXY=${qingniu}
    # - go get github.com/gocolly/colly/v2/debug
    # - go run rate_limit.go
    # - go get github.com/gocolly/colly/v2